version: '2'

services:
  web:
    build:
      context : ./docker/web
    entrypoint: '/start-reload.sh'
    volumes:
      - .:/app:rw
    ports:
      - '5000:80'
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: 'api'
    ports:
      - '5001:3306'
    volumes:
      - mysqldb_volume:/var/lib/mysql/
volumes:
  mysqldb_volume:
